# NOTE: Configured for XBOX ONE Wired USB GamePad

# Home, Select, and Start Buttons
int8 home_button # 0 or 1
int8 select_button # 0 or 1
int8 start_button # 0 or 1

# Bumpers
int8 left_bumper # 0 or 1
int8 right_bumper # 0 or 1

# ABXY Buttons
int8 a_button # 0 or 1
int8 b_button # 0 or 1
int8 x_button # 0 or 1
int8 y_button # 0 or 1

# D-Pad
int8 d_pad_x # Value for X-Axis of D-Pad
int8 d_pad_y # Value for Y-Axis of D-Pad

# Triggers
float32 left_trigger # Value for Percent Applied
float32 right_trigger # Value for Percent Applied

# Thumbsticks
float32 left_stick_x # Value for Percent Applied
float32 left_stick_y # Value for Percent Applied
float32 right_stick_x # Value for Percent Applied
float32 right_stick_y # Value for Percent Applied